# TODO: Add Time that Displays after 2200
# TODO: Add Music if playing
# TODO: See if I can make the prompt a color script gradient changes on error

#format = """
#[┌─────────────────\\( ](bold green)$battery$directory[\\)](bold green)
#[│](bold green)
#[└─$character](bold green)"""

[character]
success_symbol = "[❯](#ffb86c)[❯](#bd93f9)[❯](#50fa7b)"
error_symbol = "[❯](#ff5555)[❯](#ff5555)[❯](#ff5555)"
vicmd_symbol = "[N](#bd93f9)"

[directory]
# Coloring the directory in the format variable doesn't seem to 
# work. Uses the "color" of the ansi color name.
style = "bold white" 
format = "[ ](bold blue) [$path]($style)[$read_only]($read_only_style) "
