#!/usr/bin/env bash

# D R A C U L A
  BACKGROUND="#282a36"
  CURRENT_LINE="#44475a"
  FOREGROUND="#f8f8f2"	
  COMMENT="#6272a4"	
  CYAN="#8be9fd"
  GREEN="#50fa7b"
  ORANGE="#ffb86c"	
  PINK="#ff79c6"
  PURPLE="#bd93f9"	
  RED="#ff5555"
  YELLOW="#f1fa8c"
