#!/usr/bin/env bash

# Colors
source $HOME/.config/sketchybar/colors

DATE='
  sketchybar -m --set date label="$(date "+%a %d. %b")"
'

TIME='
  sketchybar -m --set time label="$(date "+%H:%M")"
'

sketchybar -m --add       item               time             right                                        \
              --set       time               update_freq=2                                                 \
                                             label.padding_right=15                                          \
                                             script="$TIME"                                                  \
                                                                                                            \
              --add       item               date             right                                        \
              --set       date               update_freq=60                                                \
                                             label.padding_right=15                                          \
                                             label.padding_left=15                                          \
                                             script="$DATE" \
  --add bracket date_time                 \
    time                                        \
    date                                            \
  --set date_time                          \
  background.color="0x96${CURRENT_LINE:1}"      \
  background.corner_radius=4                    \
  background.height=24
