# TODO: Use bat for fzf
# TODO: Function to search man pages with FZF and Batman https://github.com/eth-p/bat-extras/blob/master/doc/batman.md
# TODO: Setup Prettier maybe alias pretty bat afterwards
# TODO: Alias batdiff
# TODO: Autocomplete suggestion with tab, may mess with fzf menu?
# TODO: Make All Aliases check for programs if not installed by default
# TODO: Create Fast Syntax Highlighting theme for Dracula
# TODO: If the buffers empty set left or right arrow to ctrl + r history search
# FIXME: Undo does one letter at a time unless word is pasted
# FIXME: Subsearch not showing history below
# FIXME: opt + delete kills to next space 

# P A T H S 
# User Binaries
path=("$HOME/.config/bin" $path)
# Rust Binaries
path=("$HOME/.asdf/installs/rust/1.57.0/bin" $path)
# export to sub-processes (make it inherited by child processes)
export PATH

# Zellij Envs
ZELLIJ_CONFIG_DIR=/.config/zellij

# A S D F
## Init ASDF
### NOTE: This has to be initialized before any ruby configurations. 
    ##  Like colorls
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# B R E W
## Turn off analytics
export HOMEBREW_NO_ANALYTICS=1
## Add to $PATH ** Instructions state this should be in .zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# A N T I B O D Y
## Init Antibody
source <(antibody init)
## Plugins
antibody bundle Aloxaf/fzf-tab
antibody bundle zsh-users/zsh-autosuggestions
antibody bundle ohmyzsh/ohmyzsh path:lib/history.zsh
antibody bundle hlissner/zsh-autopair
### NOTE: Should be loaded after History Substring and likely last
antibody bundle zdharma-continuum/fast-syntax-highlighting 

# F Z F - T A B  C O N F I G
## disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
## set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
## set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
## preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'colorls --almost-all --git-status --group-directories-first --hyperlink --report --color=always $realpath'
## switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'

# B I N D K E Y S
## Undo
### NOTE: Set in iTerm: cmd+z sends escape code below
bindkey "^[åΩ" undo 

## Redo
### NOTE: Set in iTerm: cmd+z sends escape code below
bindkey "^[Ωå" redo

# C O L O R L S
## Enable Completions
source $(dirname $(gem which colorls))/tab_complete.sh

# A U T O L S
auto-ls() {
   colorls --almost-all --git-status --group-directories-first --hyperlink --report --color=always
}
chpwd_functions=(auto-ls $chpwd_functions)

# C A S E  I N S E N S I T I V E  S U G G E S T I O N S
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# H I S T O R Y  S U B S E A R C H  C O N F I G
bindkey '^[[A' history-beginning-search-backward 
bindkey '^[[B' history-beginning-search-forward 

# S T A R S H I P
## Init Starship
eval "$(starship init zsh)"
## Prefer Config in it's own folder
export STARSHIP_CONFIG=~/.config/starship/starship.toml

# F Z F
## Add FZF functionality
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
## Dracula Theme
export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

# N A V I 
eval "$(navi widget zsh)"
export NAVI_CONFIG="$HOME/.config/navi/config.yaml"

# C O M P L E T I O N S
## Path to ZSH Completions
fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
## Load available completions
### NOTE: This has to be initialized after all completion settings
autoload -Uz compinit
compinit

# A L I A S E S
alias bat="bat --theme=dracula_italicized --italic-text=always"
if [ -f /opt/homebrew/bin/trash ]; then alias rm="/opt/homebrew/bin/trash"; fi

alias ls="colorls --almost-all --git-status --group-directories-first --hyperlink --report --color=always"

dotpush() {
  sed -i '' -e '1,/\# TODOs/!d' $HOME/.dots/README.md

    rg -g '!dotbot/' -g '!vscode/' -r '- [ ]' --line-number --trim --heading -e '^\s*# TODO:' -e '^\s*-- TODO:' $HOME/.dots | sed -E -e 's/^([0-9]+)\:(.*)/\2 __Line: \1__/g' -e 's/(-.+\])(.*)( __.*)/\1 \(\3\) \-\2/g' -e 's/(\/Users\/brandon\/.dots\/)(.*)/\#\# \[\2\]\(\2\)/g' >> $HOME/.dots/README.md

  git -C $HOME/.dots add --all && git -C $HOME/.dots commit -m \"$1\" && git -C $HOME/.dots push -u origin main
}

private_dotpush() {

  # Pull New Files
  git pull origin
  
  # Update Readme
  sed -i '' -e '1,/\# TODOs/!d' $HOME/.private_dots/README.md
    rg -g '!dotbot/' -g '!vscode/' -r '- [ ]' --line-number --trim --heading -e '^\s*# TODO:' -e '^\s*-- TODO:' $HOME/.private_dots | sed -E -e 's/^([0-9]+)\:(.*)/\2 __Line: \1__/g' -e 's/(-.+\])(.*)( __.*)/\1 \(\3\) \-\2/g' -e 's/(\/Users\/brandon\/.private_dots\/)(.*)/\#\# \[\2\]\(\2\)/g' >> $HOME/.private_dots/README.md

  # Add any other new files to the secret
  git secret add *

  # Git Secret Hide All Files
  git-secret hide

  # Add New Secret Files, Commit them, and push them
  git -C $HOME/.private_dots add --all && git -C $HOME/.private_dots commit -m \"$1\" && git -C $HOME/.private_dots push -u origin main
}

# ZLE Widget to move cursor to beginning of the buffer
# zle -N adds it to zsh as a widget so that it can be
# bound
_beginning_of_buffer() { 
  CURSOR=0
}
zle -N _beginning_of_buffer

_end_of_buffer() {
  CURSOR="${#BUFFER}"
}
zle -N _end_of_buffer

bindkey "^[åå" _beginning_of_buffer
bindkey "^[ΩΩ" _end_of_buffer
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# R A N G E R 
## Dev Icons
export RANGER_DEVICONS_SEPARATOR="  "

# E N V  V A R I A B L E S
export EDITOR="nvim"

# Don't Add commands with a space at the beginning to the history filename
setopt HIST_IGNORE_SPACE
